# Generated by Django 3.1.7 on 2021-08-01 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profilo', 'verbose_name_plural': 'Profili'},
        ),
    ]
