# Generated by Django 3.1.7 on 2021-07-31 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domande', '0002_auto_20210731_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='domanda',
            name='gruppo',
            field=models.CharField(choices=[('Gruppo A', 'GRUPPO A'), ('Gruppo B', 'GRUPPO B'), ('Gruppo C', 'GRUPPO C'), ('Gruppo D', 'GRUPPO D'), ('Gruppo HT', 'GRUPPO HT')], default='Gruppo A', max_length=10),
        ),
        migrations.AlterField(
            model_name='domanda',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='argomento', to='domande.materia'),
        ),
    ]
