# Generated by Django 3.1.7 on 2021-07-31 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domande', '0003_auto_20210731_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='domanda',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default='2021-07-31 10:30'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='domanda',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domande.materia'),
        ),
    ]
