# Generated by Django 3.1.7 on 2021-07-31 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domande', '0004_auto_20210731_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='domanda',
            name='punteggio',
            field=models.IntegerField(default=1, editable=False, help_text='Quante volte è stata ripetuta questa domanda'),
        ),
        migrations.AlterField(
            model_name='domanda',
            name='gruppo',
            field=models.CharField(choices=[('Canale A', 'CANALE A'), ('Canale B', 'CANALE B'), ('Canale C', 'CANALE C'), ('Canale D', 'CANALE D'), ('Canale HT', 'CANALE HT')], default='Canale A', max_length=10),
        ),
    ]
