# Generated by Django 3.1.7 on 2021-07-31 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domande', '0005_auto_20210731_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domanda',
            name='id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
