# Generated by Django 3.1.7 on 2021-07-31 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domande', '0006_auto_20210731_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='domanda',
            name='anno',
            field=models.CharField(choices=[('I', 'Primo'), ('II', 'Secondo'), ('III', 'Terzo'), ('IV', 'Quarto'), ('V', 'Quinto'), ('VI', 'Sesto')], default='I', max_length=3),
        ),
        migrations.AlterField(
            model_name='domanda',
            name='punteggio',
            field=models.IntegerField(default=1, help_text='Quante volte è stata ripetuta questa domanda'),
        ),
    ]
