# Generated by Django 3.1.7 on 2021-07-31 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domande', '0007_auto_20210731_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='domanda',
            name='username',
            field=models.TextField(default='', editable=False),
        ),
    ]
