# Generated by Django 3.1.7 on 2021-07-31 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domande', '0008_domanda_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='domanda',
            name='argomento',
            field=models.CharField(default='TBD', max_length=400),
        ),
        migrations.AlterField(
            model_name='domanda',
            name='username',
            field=models.TextField(default=''),
        ),
    ]
