# Generated by Django 3.1.7 on 2021-07-31 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domande', '0009_auto_20210731_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domanda',
            name='argomento',
        ),
    ]
